### ISSUE TITLE
Capability to erase all LEDs

### ISSUE THREAD

**Issue by MER000** [roger-selzler/SYSC3010Lab4#3]
Add a function in the [device.py] script to continuously check the joystick and set all the values of the LEDs to [0,0,0] if/when the joystick is sense pressed down.

Inside this newly created function you should call (clear_leds(device_id)) from the Backend to clear all LEDs. NOT calling the sense.set_pixels(...) function (otherwise the database will not be updated). The device id can be acquired with the function get_device_id(), also from the Backend class.

**Comment by jrgreen7** [comment]
This issue should be opened on your own private "fork" of this public repo... This is the template repo that all student groups should be forking.
